backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "jobs"
    label: "Jobs"
    files:
      - name: "all_jobs"
        label: "Job Listings"
        file: "content/data.json" 
        fields:
          - {label: "Job List", name: "jobs", widget: "list", fields: [
              {label: "Job Title", name: "title", widget: "string"},
              {label: "Company Name", name: "company", widget: "string"},
              {label: "City", name: "city", widget: "string"},
              {label: "Description", name: "body", widget: "markdown"}
            ]}
