backend:
  name: git-gateway
  branch: main  # تأكد واش Branch عندك سميتها main أو master

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "jobs"
    label: "Jobs"
    folder: "content/jobs" # هنا CMS غايخزن العروض (كل عرض فملف)
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Job Title", name: "title", widget: "string"}
      - {label: "Company", name: "company", widget: "string"}
      - {label: "City", name: "city", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "body", widget: "markdown"}
      - {label: "Apply Link", name: "link", widget: "string"}
