backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
# public_folder: "/images/uploads"

collections:
  - name: "jobs"
    label: "Jobs"
    files:
      - name: "all_jobs"
        label: "All Jobs"
        file: "data/jobs.json"
        citation: true
        fields:
          - { label: "Jobs List", name: "jobs", widget: "list", fields: [
              { label: "Title", name: "title", widget: "string" },
              { label: "Company Name", name: "company", widget: "string" },
              { label: "City", name: "city", widget: "select", options: ["الدار البيضاء", "الرباط", "مراكش", "طنجة", "أكادير", "عن بعد", "أخرى"] },
              { label: "Job Type", name: "type", widget: "select", options: ["Full Time", "Remote", "Freelance", "Internship"], default: "Full Time" },
              { label: "Salary", name: "salary", widget: "string", required: false, hint: "e.g. 8000 - 10000 DH" },
              { label: "Description", name: "description", widget: "markdown" },
              { label: "Apply Link", name: "link", widget: "string" },
              { label: "Posted Date", name: "date", widget: "datetime", default: "", date_format: "DD/MM/YYYY", time_format: false }
            ] 
          }
